### PR TITLE
Don't Merge: CLA test

### PR DESCRIPTION
**Pull request by thombehrens**
Checking to see if contributors are prompted to sign the CLA

### CODE REVIEW

**Comment by coriobriensfdo** [comment]
Thanks @thombehrens! Curious, were you prompted to sign it or did it automatically apply the cla:signed label?

**Comment by thombehrens** [comment]
It automatically assigned the label. Did it transfer my CLA signature from the NPSP repo, or the VS Code extensions repo?

**Comment by coriobriensfdo** [comment]
@thombehrens I know you've signed a paper CLA for us in the past, but have you signed an automated one on another repo before? If so, then yep that would be why as it only needs you to sign once.

**Comment by thombehrens** [comment]
yes I have 🙂

**Comment by coriobriensfdo** [comment]
Ok perfect, then we know it's referenced as expected. Success! :) 

We can close this now @dvenor

**Comment by dvenor** [comment]
Closing the PR as it was only a test.

**Pull request closed without merging**
